Mengenal parameter header dan skiprows
- Fungsi 'header', untuk menentukan header dari dataframe ada di baris berapa
- Ex: df = pd.read_csv('iris_error.csv', header=2)
- Fungsi 'skiprows', untuk menentukan baris berapa saja yang akan di lewat
- Ex: df = pd.read_csv('iris_error.csv', header=2, skiprows=[5,6])

In [1]:
import pandas as pd
print(pd.__version__)

1.3.4

In [5]:
df = pd.read_csv('C:/Users/Rosi Rachel/Desktop/Data Frame/iris_error.csv')
df.head(8)

    1            5.1           3.5            1.4           0.2   Iris-error
0   2            4.9           3.0            1.4           0.2   Iris-error
1  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2   Iris-error
5   6            5.4           3.9            1.7           0.4   Iris-error
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa

In [6]:
df = pd.read_csv('C:/Users/Rosi Rachel/Desktop/Data Frame/iris_error.csv', header=2, skiprows=[5,6])
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   3            4.7           3.2            1.3           0.2  Iris-setosa
1   4            4.6           3.1            1.5           0.2  Iris-setosa
2   7            4.6           3.4            1.4           0.3  Iris-setosa
3   8            5.0           3.4            1.5           0.2  Iris-setosa
4   9            4.4           2.9            1.4           0.2  Iris-setosa